import 'package:dalal_app/constants/imports.dart';

class string{
  static const appName = "દલાલ";
}

class LocateString extends Translations
{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'appTitle': 'Dalal',
      'mobileNo': 'Mobile Number',
      'next': 'Submit',
      'otpsend': 'Otp Sended',
      'otpresend': 'Resent Otp',
      'add':'Add',
      'postadd': 'Add Post',
      'mypost':'My Post',
      'delete':'Delete',
      'title':'Title',
      'link':'Link',
      'home': 'Home',
      'mydetails': 'My Details',
      'tv': 'Kishan Videos',
      'favorite':'Favorite',
      'seller': 'Seller ',
      'name': 'Name',
      'email': 'E-Mail',
      'address': 'Address',
      'state': 'State',
      'taluko': 'Taluka',
      'city': 'City',
      'edit': 'Edit',
      'date': 'Date',
      'producttitle': 'Product',
      'price': 'Price',
      'description': 'Description',
      'helpline': 'HelpLine Number',
      'exit': 'Exit',
      'retry': 'Retry',
    },
    'hi_IN':{
      'appTitle': 'दलाल',
      'mobileNo': 'मोबाइल नंबर',
      'next': 'आगे बढ़ो',
      'otpsend': 'Otp भेज दिया',
      'otpresend': 'पुनः भेजें',
      'add':'डालो',
      'postadd': 'पोस्ट डालो',
      'mypost':'मेरा पोस्ट',
      'delete':'मिटाना',
      'title':'शीर्षक',
      'link':'लिंक',
      'home': 'होम',
      'mydetails': 'मेरा विवरण',
      'tv': 'किसान टीवी',
      'favorite':'पसंदीदा',
      'seller': 'विक्रेता',
      'name': 'नाम',
      'email': 'ईमेल',
      'address': 'पता',
      'state': 'राज्य',
      'taluko': 'तालुका',
      'city': 'शहर',
      'edit': 'संपादन करो',
      'date': 'दिनांक',
      'producttitle': 'उत्पाद',
      'price': 'कीमत',
      'description': 'विवरण',
      'helpline': 'हेल्पलाइन नंबर',
      'exit': 'બહાર',
      'retry':'पुन: प्रयास करें',
    },
    'gu_IN':{
      'appTitle' : 'દલાલ',
      'mobileNo': 'મોબાઈલ નંબર',
      'next': 'આગળ વધો',
      'otpsend': 'Otp મોકલેલ ',
      'otpresend': 'ફરીથી મોકલો ',
      'add':'ઉમેરો',
      'postadd': ' પોસ્ટ નાખો',
      'mypost':'મારી પોસ્ટ',
      'delete':'કાઢી નાખો',
      'title':'શીર્ષક',
      'link':'લિંક્સ',
      'home': 'હોમ',
      'mydetails': 'મારી વિગતો',
      'tv': 'કિશાન ટીવી',
      'favorite':'મનપસંદ',
      'seller': 'વેચનાર',
      'name': 'નામ',
      'email': 'ઈ-મેલ',
      'address': 'સરનામું',
      'state': 'રાજ્ય',
      'taluko': 'તાલુકો',
      'city': 'જિલ્લો',
      'edit': 'સુધારો',
      'date': 'તારીખ',
      'producttitle': 'વસ્તુ',
      'price': 'કિંમત',
      'description': 'વર્ણન',
      'helpline': 'હેલ્પલાઇન નંબર',
      'exit': 'બહાર',
      'retry':'ફરી પ્રયાસ કરો',
    }

  };
}